#!/bin/bash
export DOTFILES="$HOME/dotfiles"

echo ""
echo "Handling Pre-reqs for macOS"
echo ""

echo " › Setting up Xcode Command Line Tools"

xcode-select --install

echo " › Installing and Upgrading Homebrew"
if [ -f "$(which brew)" ]; then
  brew update
else
  /usr/bin/ruby -e "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/install)"
fi

echo " › Installing Common Utilities"
brew install git
brew install rename
brew install tree
brew install fswatch
brew install coreutils
brew install exa # better ls

echo " › Installing Editor and Friends"
brew install vim neovim # editor
brew install fzf fd # file search
brew install ack the_silver_searcher the_platinum_searcher # text search

echo ""
echo "DONE"
